<?php

return [
    'communes_haute_vienne' => [
        'Aixe-sur-Vienne',
        'Ambazac',
        'Bellac',
        'Bessines-sur-Gartempe',
        'Chalus',
        'Chaptelat',
        'Condat-sur-Vienne',
        'Couzeix',
        'Darnac',
        'Eymoutiers',
        'Isle',
        'Le Palais-sur-Vienne',
        'Limoges',
        'Magnac-Laval',
        'Mortemart',
        'Nantiat',
        'Nedde',
        'Nexon',
        'Oradour-sur-Glane',
        'Panazol',
        'Peyrilhac',
        'Rochechouart',
        'Saint-Junien',
        'Saint-Laurent-sur-Gorre',
        'Saint-Léonard-de-Noblat',
        'Saint-Priest-Taurion',
        'Saint-Savin',
        'Saint-Yrieix-la-Perche',
        'Sauviat-sur-Vige',
        'Sérilhac',
    ],
];
